# -*- coding: utf-8 -*-
"""Circuito_RLC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zw-rXX0XfRo3x3nHtUJ7D0uRPEQI9-SB

## Circuito RLC Série

Para simular um circuito RLC, você precisará resolver as equações diferenciais que regem o circuito. Um circuito RLC normalmente consiste em um resistor (R), um indutor (L) e um capacitor (C) conectados em série, e seu comportamento pode ser descrito pela seguinte equação diferencial:

$$
V_f(t) - Ri_c(t) - L \frac{di_c(t)}{dt} - \frac{1}{C}\int i_c(t)dt = 0
$$
"""

import numpy as np
import matplotlib.pyplot as plt

# Considere os seguintes parâmetros no circuito:

R = 1.0  # Resistência (Ohms)
L = 1.0  # Inductância (Henry)
C = 1.0  # Capacitância (Farads)
V0 = 1.0 # Tensão na fonte (Volts)

# Parâmetros da simulação
dt = 0.01  # Step time (seconds)
T = 10.0   # tempo total de simulação (seconds)
num_steps = int(T / dt)

# Iniciação dos parâmetros a serem simulados
t = np.linspace(0, T, num_steps)
I = np.zeros(num_steps)  # corrente elétrica presente no circuito
Vc = np.zeros(num_steps) # Voltagem sobre o capacitor

# Condições Iniciais
I[0] = 0
Vc[0] = 0

# Método de Euler
for n in range(num_steps - 1):
    # Calcula a derivada da corrente
    dI = (V0 - R * I[n] - Vc[n]) / L * dt

    # Equações de Euler
    I[n + 1] = I[n] + dI

    Vc[n + 1] = Vc[n] + I[n] / C * dt

# Resultados obtidos
plt.figure(figsize=(12, 6))

plt.subplot(2, 1, 1)
plt.plot(t, I)
plt.title('Corrente presente no circuito RLC série')
plt.xlabel('Tempo (s)')
plt.ylabel('Corrente (A)')
plt.grid()

plt.subplot(2, 1, 2)
plt.plot(t, Vc)
plt.title('Voltagem sobre o capacitor')
plt.xlabel('Tempo (s)')
plt.ylabel('Voltagem (V)')
plt.grid()

plt.tight_layout()
plt.show()

"""### Diagrama de Fase (retrato de fases)"""

# Cria uma grade para o campo direcional
I_grid, Vc_grid = np.meshgrid(np.linspace(-2.0, 2.0, 20), np.linspace(-2.0, 2.0, 20))

# Calcula o campo direcional
dI_grid = (V0 - R * I_grid - Vc_grid) / L
dVc_grid = I_grid / C

# Normaliza os vetores direcionais para uma melhor visualização
magnitude = np.sqrt(dI_grid**2 + dVc_grid**2)
#Trata possíveis divis~]oes por zero
magnitude[magnitude == 0] = 1
dI_grid /= magnitude
dVc_grid /= magnitude

# Fator escala relativa ao comprimento dos vetores
scale_factor = 0.15

# Resultados obtidos
plt.figure(figsize=(12, 6))

plt.quiver(I_grid, Vc_grid, dI_grid * scale_factor, dVc_grid * scale_factor,
           angles='xy', scale_units='xy', scale=1, color='blue', headlength=3, headwidth=2)

plt.plot(I, Vc, color='red', label='Trajetória / evolução do circuito RLC série')

plt.title('Campo direcional e evolução do circuito RLC')
plt.xlabel('Corrente (A)')
plt.ylabel('Voltagem sobre o Capacitor (V)')
plt.legend()
plt.grid()
plt.show()

