# -*- coding: utf-8 -*-
"""Projeto Unidade 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104aRBJAX1B1DC53PtcBKCpMEtG6s-7Nr
"""

#Questão 1
import numpy as np
import matplotlib.pyplot as plt

m1 = 20
m2 = 20
k1 = 1000
k2 = 2000
b1 = 1
b2 = 5

t0 = 0
tf = 2000
dt = 0.001

t = np.arange(t0, tf, dt)
x1 = np.zeros(len(t))
x2 = np.zeros(len(t))
v1 = np.zeros(len(t))
v2 = np.zeros(len(t))

def F(n):
  if n == 0:
    return 100
  else:
    return 0

def dv1(n):
  return ((-k1-k2) * x1[n] + (-b1-b2) * v1[n] + k2 * x2[n] + b2 * v2[n])/m1

def dv2(n):
  return  (k2*x1[n] + b2*v1[n] - k2*x2[n] - b2*v2[n] + F(n))/m2

x1[0] = 0
x2[0] = 0
v1[0] = 0
v2[0] = 0

for n in range(len(t)-1):
    v1[n + 1] = v1[n] + dv1(n) * dt
    v2[n + 1] = v2[n] + dv2(n) * dt
    x1[n + 1] = x1[n] + v1[n] * dt
    x2[n + 1] = x2[n] + v2[n] * dt

plt.figure(figsize=(6, 4))
plt.plot(t, x1, label='Posição x1')
plt.plot(t, x2, label='Posição x2')
plt.xlabel('Tempo (s)')
plt.ylabel('Posição (m)')
plt.legend()
plt.title('Gráfico de Posições x1 e x2 em função do tempo')
plt.grid(True)
plt.show()

x1_values = np.linspace(-0.5, 0.5, 20)
x2_values = np.linspace(-0.5, 0.5, 20)
X1, X2 = np.meshgrid(x1_values, x2_values)

U = X2
V = (-k1 * X1 - b1 * X2 + k2 * (X2 - X1)) / m1

plt.figure(figsize=(6, 4))
plt.quiver(X1, X2, U, V, color='blue')
plt.plot(x1, v1, color='red', label='Trajetória x1/v1')
plt.plot(x2, v2, color='green', label='Trajetória x2/v2')
plt.xlabel('Posição (x)')
plt.ylabel('Velocidade (v)')
plt.title('Diagrama de Fase do sistema massa-mola-amortecedor')
plt.legend()
plt.grid(True)
plt.show()

#Questão 2

import numpy as np
import matplotlib.pyplot as plt

a = 1
b = 0.25
c = 0.01
d = 0.02
e = 0.02
h = 0
x0 = 50
y0 = 10
t0 = 0
tf = 200
dt = 0.001
num_steps = int((tf - t0) / dt)

x = np.zeros(num_steps)
y = np.zeros(num_steps)
t = np.linspace(t0, tf, num_steps)

x[0] = x0
y[0] = y0

for n in range(num_steps - 1):
    dx = x[n] * (a - c * x[n] - d * y[n]) * dt
    dy = (-y[n] * (b - e * x[n]) - h) * dt

    x[n + 1] = x[n] + dx
    y[n + 1] = y[n] + dy

plt.figure(figsize=(8, 4))
plt.plot(t, x, label='Presas (x)')
plt.plot(t, y, label='Predadores (y)')
plt.title('Evolução das Populações')
plt.xlabel('Tempo')
plt.ylabel('População')
plt.legend()
plt.grid()

x_values = np.linspace(0, max(x) * 1.1, 20)
y_values = np.linspace(0, max(y) * 1.1, 20)
X, Y = np.meshgrid(x_values, y_values)

U = X * (a - c * X - d * Y)
V = (-Y * (b - e * X) - h)

plt.figure(figsize=(8,4))
plt.quiver(X, Y, U, V, color='blue')
plt.plot(x, y, color='red', label='Trajetória (x/y)')
plt.title('Diagrama de Fase do Sistema Presa-Predador')
plt.xlabel('Presas (x)')
plt.ylabel('Predadores (y)')
plt.legend()
plt.grid()

#Questão 3
import numpy as np
import matplotlib.pyplot as plt

L = 2
L0 = 1
k = 40
m = 1
g = 9.81
theta = 3 * np.pi / 4

t0 = 0
tf = 20
dt = 0.001
num_steps = int((tf - t0) / dt)

x1 = np.zeros(num_steps)
x2 = np.zeros(num_steps)
t = np.linspace(t0, tf, num_steps)

x1[0] = 0
x2[0] = 0

for n in range(num_steps - 1):
    dx1 = -(1/L) * (g * np.sin(theta) + 2 * x1[n] * x2[n]) * dt
    dx2 = (1/m) * (m * L * x1[n]**2 - k * (L - L0) + m * g * np.cos(theta)) * dt

    x1[n + 1] = x1[n] + dx1
    x2[n + 1] = x2[n] + dx2

plt.figure(figsize=(8, 4))
plt.plot(t, x1, label='Posição (x1)')
plt.plot(t, x2, label='Velocidade (x2)')
plt.xlabel('Tempo (s)')
plt.ylabel('Magnitude')
plt.legend()
plt.title('Gráfico de Posição e Velocidade')
plt.tight_layout()
plt.show()

x1_values = np.linspace(-15, 15, 20)
x2_values = np.linspace(-15, 15, 20)
X1, X2 = np.meshgrid(x1_values, x2_values)

U = -(1/L) * (g * np.sin(theta) + 2 * X1 * X2)
V = (1/m) * (m * L * X1**2 - k * (L - L0) + m * g * np.cos(theta))

plt.figure(figsize=(8, 4))
plt.quiver(X1, X2, U, V, color='blue')
plt.plot(x1, x2, color='red', label='Trajetória / Evolução')
plt.xlabel('Posição (x1)')
plt.ylabel('Velocidade (x2)')
plt.title('Diagrama de Fase')
plt.legend()
plt.grid(True)
plt.show()