# -*- coding: utf-8 -*-
"""Sinais&Sistemas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOIQmTgTQAuAIWcSn19lOiWT1eoAyaqt
"""

# DFT and FFT Implementation for Google Colab

import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft
import ipywidgets as widgets
from IPython.display import display, clear_output

def dft_vandermonde(x):
    N = len(x)
    # Construct Vandermonde matrix W
    n = np.arange(N)
    k = n.reshape((N, 1))
    W = np.exp(-2j * np.pi * n * k / N)

    # Calculate DFT
    X = np.dot(W, x)
    return X

def plot_spectrum(X, N, title_prefix=""):
    k = np.arange(N)
    amplitude = np.abs(X)
    phase = np.angle(X)

    plt.figure(figsize=(12, 6))

    # Amplitude spectrum
    plt.subplot(2, 1, 1)
    plt.stem(k, amplitude)
    plt.title(f'{title_prefix}Espectro de Amplitude (|X[k]|)')
    plt.xlabel('Índice de Frequência (k)')
    plt.ylabel('Magnitude')
    plt.grid(True)

    # Phase spectrum
    plt.subplot(2, 1, 2)
    plt.stem(k, phase)
    plt.title(f'{title_prefix}Espectro de Fase (∠X[k])')
    plt.xlabel('Índice de Frequência (k)')
    plt.ylabel('Fase (radianos)')
    plt.grid(True)

    plt.tight_layout()
    plt.show()

def run_analysis(N_value, signal_type, method):
    clear_output(wait=True)

    # Generate input signal
    if signal_type == "1. [1,2,3,4,4,3,2,1]":
        if N_value == 8:
            x = np.array([1, 2, 3, 4, 4, 3, 2, 1])
        else:
            print("Para esse sinal, apenas N=8 é válido")
            return
    elif signal_type == "2. cos(πn/4)":
        n = np.arange(N_value)
        x = np.cos(np.pi * n / 4)
    else:
        print("Tipo de sinal inválido")
        return

    # Calculate and plot
    if method == "Ambos":
        plt.figure(figsize=(12, 4))
        plt.stem(np.arange(N_value), x)
        plt.title(f'Sinal de Entrada x[n] (N={N_value})')
        plt.xlabel('Amostra (n)')
        plt.ylabel('Amplitude')
        plt.grid(True)
        plt.show()

        print("\nResultados usando Matriz de Vandermonde:")
        X_v = dft_vandermonde(x)
        plot_spectrum(X_v, N_value, "DFT (Vandermonde) - ")

        print("\nResultados usando FFT:")
        X_fft = fft(x)
        plot_spectrum(X_fft, N_value, "FFT - ")

        # Compare differences
        print("\nComparação entre os métodos:")
        print(f"Diferença máxima entre DFT e FFT: {np.max(np.abs(X_v - X_fft)):.2e}")

    elif method == "Vandermonde":
        plt.figure(figsize=(12, 4))
        plt.stem(np.arange(N_value), x)
        plt.title(f'Sinal de Entrada x[n] (N={N_value})')
        plt.xlabel('Amostra (n)')
        plt.ylabel('Amplitude')
        plt.grid(True)
        plt.show()

        print("\nResultados usando Matriz de Vandermonde:")
        X_v = dft_vandermonde(x)
        plot_spectrum(X_v, N_value, "DFT (Vandermonde) - ")

    elif method == "FFT":
        plt.figure(figsize=(12, 4))
        plt.stem(np.arange(N_value), x)
        plt.title(f'Sinal de Entrada x[n] (N={N_value})')
        plt.xlabel('Amostra (n)')
        plt.ylabel('Amplitude')
        plt.grid(True)
        plt.show()

        print("\nResultados usando FFT:")
        X_fft = fft(x)
        plot_spectrum(X_fft, N_value, "FFT - ")

    else:
        print("Método inválido")

# Create interactive widgets
N_widget = widgets.Dropdown(
    options=[8, 16],
    value=8,
    description='N (tamanho):',
    disabled=False,
)

signal_widget = widgets.Dropdown(
    options=["1. [1,2,3,4,4,3,2,1]", "2. cos(πn/4)"],
    value="1. [1,2,3,4,4,3,2,1]",
    description='Sinal de entrada:',
    disabled=False,
)

method_widget = widgets.Dropdown(
    options=["Ambos", "Vandermonde", "FFT"],
    value="Ambos",
    description='Método:',
    disabled=False,
)

run_button = widgets.Button(description="Executar Análise")

def on_button_click(b):
    run_analysis(N_widget.value, signal_widget.value, method_widget.value)

run_button.on_click(on_button_click)

# Display the widgets
display(widgets.VBox([N_widget, signal_widget, method_widget, run_button]))

# Sample run instructions
print("\nInstruções:")
print("1. Selecione o tamanho da DFT (N=8 ou N=16)")
print("2. Escolha o sinal de entrada")
print("3. Selecione o método de cálculo")
print("4. Clique em 'Executar Análise'")
print("\nNota: O primeiro sinal só está definido para N=8")